### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jamesfzhang** [tinycreative/react-native-dropbox-chooser#1]
Is this public? Can't seem to install via npm. Thanks!

**Comment by browniefed** [comment]
Sorry, I forgot to publish this to NPM will take care of that.

**Comment by browniefed** [comment]
Published, feel free to `npm install react-native-dropbox-chooser --save`. Let me know if you have issues.

**Comment by jamesfzhang** [comment]
Thanks! I'm just bummed that Dropbox's DBChooser doesn't support the multi-select option that the JS library has :(.
